#!/bin/bash

if [[ $NODE_ENV == production ]]; then
  node server.js
else
  trap 'kill $(jobs -p)' EXIT
  redis-server redis.conf &
  watchify --extension=.jsx client.js -o static/bundle.js -v &
  node-dev scripts/worker &
  node-dev server.js
fi
